### ISSUE TITLE
anchored top part / info

### ISSUE THREAD

**Issue by icpantsparti2** [arkenfox/gui#4]
> add info that says what this is (that links to AF user.js repo)

> move version number here

<img src="https://user-images.githubusercontent.com/101484718/161612841-d0b536f4-27e3-4a20-8b8d-3d51e1e8d338.png" width="400" />

@Thorin-Oakenpants thoughts?

The prompt line immediately above the table, that scrolls upwards when the table scrolls.  changing/adding there is another option.

**Comment by Thorin-Oakenpants** [comment]
you're onto it, we're really just playing around with cosmetics

fair warning, I have not looked at a single piece of code

I'd like to get it to a single line e.g. we don't need to say "see filter button" (it should be intuitive), we can re-use collapse/expand into a single button, and we can put an info `<detail>` at the far right, along with the version number e.g `▶ About` (which expands the nav bar taller and exposes a single line of info?)  and `v98` (i.e we don't need to say this is arkenfox)

I would use a different darker background color for the sticky "nav bar" at the top and give it a bottom border

So something like this
```
[index]  [collapse/expand] [filter] search [_______]          v98 [about] 
```

**Comment by icpantsparti2** [comment]
* todo: fix position of [ver] [About] and the message

> single line of info

* what message shall we put, it just shows repo url at the moment, and needs repositing

**Comment by Thorin-Oakenpants** [comment]
Just stick in some [`lorem ipsum`](https://loremipsum.io/) for now - my guess is it'll end up as two sentences or 20-30 words long

I'm still not sure how I want this to all look just yet. I want to style it all, change the font sizes, add a max width (and a min width). I think the name arkenfox should show (otherwise there's nothing to say _what_ it is, but I worry that on smaller widths there isn't enough room (when it wraps to a new line it's a bit naff at the moment) and the search box is too short (it should be big but shrink when needed)

I need to think about the UI, make a non-functioning mockup. Maybe the about bit opens an overlay popup.

**Comment by Thorin-Oakenpants** [comment]
desktop min, the browser cannot get below 454px inner or something, and I don't expect desktop users to be less than say 800 to be honest, but mobile is a different story

![minwidth](https://user-images.githubusercontent.com/16656956/161685657-8fe462e3-0155-4d56-a610-f7dabbdc580e.png)

**Comment by icpantsparti2** [comment]
Added an "About" overlay popup, and adjusted the top bar (such as buttons resize with width, ...).

**Comment by Thorin-Oakenpants** [comment]
going to be busy for a few days, but great stuff
